# Generated by Django 6.0.2 on 2026-02-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
